version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: smartfactory-db
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" # chỉ để debug, có thể bỏ khi prod
    volumes:
      - dbdata:/var/opt/mssql
      - ./database:/database
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 15 &&
      /database/init-db.sh
      "
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Pass123", "-Q", "SELECT 1"]
      interval: 10s
      retries: 10

  backend:
    build:
      context: ../../apps/backend
    container_name: smartfactory-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Server=db;Database=SmartFactory;User Id=sa;Password=YourStrong!Pass123;"
    ports:
      - "5000:80"

  frontend:
    build:
      context: ../../apps/frontend
    container_name: smartfactory-web
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  dbdata:
